# Generated by Django 4.2.18 on 2025-01-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_seen_location', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='reported_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
