# Generated by Django 4.2.18 on 2025-01-30 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_last_seen_location_reportedcase_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportedcase',
            name='details',
        ),
        migrations.RemoveField(
            model_name='reportedcase',
            name='name',
        ),
    ]
