# Generated by Django 4.2.18 on 2025-01-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_reportedcase_details_remove_reportedcase_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedcase',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
