# Generated by Django 4.2.18 on 2025-02-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_reportedcase_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportedcase",
            name="name",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
