# Generated by Django 4.2.18 on 2025-01-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedcase',
            name='photo',
            field=models.ImageField(upload_to='reported_images/'),
        ),
    ]
