# Generated by Django 4.2.18 on 2025-01-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0002_alter_reportedcase_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedcase',
            name='description',
            field=models.CharField(default='No description', max_length=255),
        ),
    ]
