# Generated by Django 4.2.18 on 2025-02-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "admin_interface",
            "0004_remove_reportedcase_details_remove_reportedcase_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reportedcase",
            name="name",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
