# Generated by Django 4.2.18 on 2025-02-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_interface", "0005_reportedcase_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportedcase",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
