# Generated by Django 4.2.18 on 2025-02-05 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_reportedcase_name"),
        ("admin_interface", "0006_alter_reportedcase_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchedcase",
            name="reported_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.reportedcase"
            ),
        ),
    ]
