# Generated by Django 4.2.18 on 2025-02-08 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0007_alter_matchedcase_reported_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeProgressedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_target', models.IntegerField()),
                ('photo', models.ImageField(upload_to='age_progressed/')),
                ('registered_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_interface.registeredperson')),
            ],
        ),
    ]
