# Generated by Django 4.2.18 on 2025-02-08 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_reportedcase_name'),
        ('admin_interface', '0008_ageprogressedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ageprogressedimage',
            name='registered_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_progressed_images', to='admin_interface.registeredperson'),
        ),
        migrations.AlterUniqueTogether(
            name='matchedcase',
            unique_together={('registered_person', 'reported_case')},
        ),
    ]
